### ISSUE TITLE
你好，请教一个问题

### ISSUE THREAD

**Issue by ghost** [didez/Clover_B360M_ITXac#1]
我的配置是8400+asrock b360m itx/ac 与您的配置差不多

我现在是DP核显输出4K，在进入系统的时候，在LOGO进度条2/3处屏幕会闪一下，之后进入系统，打开的窗口会闪烁，过一会屏幕黑一下。

请问这个问题应该用什么思路去解决呢？

**Comment by TukizHoang** [comment]
> 我的配置是8400+asrock b360m itx/ac 与您的配置差不多
> 
> 我现在是DP核显输出4K，在进入系统的时候，在LOGO进度条2/3处屏幕会闪一下，之后进入系统，打开的窗口会闪烁，过一会屏幕黑一下。
> 
> 请问这个问题应该用什么思路去解决呢？
