### ISSUE TITLE
老哥，貌似前面板的usb没有驱动起来呀

### ISSUE THREAD

**Issue by DaguDuiyuan** [didez/Clover_B360M_ITXac#2]

**Comment by conversun** [comment]
是的，貌似是会有这个问题，因为我的 ITX 主机没有前置，我是参照这个生成的 usbPort.kext，你可以试试  https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html

**Comment by DaguDuiyuan** [comment]
好的 我去弄一下 谢谢老哥
